MediaPlayerMVC/Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FireSharp.Config;
using FireSharp.Interfaces;
using FireSharp.Response;
using MediaPlayerMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;

namespace MediaPlayerMVC.Controllers
{
    public class DisplayController : Controller
    {


        IFirebaseConfig config = new FirebaseConfig
        {
            AuthSecret = "c3jEy9HFaQDxohkPvy9pXt4ss7Pil29qZLNx7TN3",
            BasePath = "https://mediaplayer-46757.firebaseio.com/"
        };

        IFirebaseClient client;

        public ActionResult Index()
        {
            client = new FireSharp.FirebaseClient(config);
            FirebaseResponse response = client.Get("Users");
           
            dynamic data = JsonConvert.DeserializeObject<dynamic>(response.Body);
           
            var list = new List<RegistrationModel>();
            foreach (var item in data)
            {
                //Console.WriteLine(JsonConvert.DeserializeObject<RegistrationModel>(((JProperty)item).Value.ToString()).Name);
                list.Add(JsonConvert.DeserializeObject<RegistrationModel>(((JProperty)item).Value.ToString()));

            }
            
            return View(list);
        }

       
    }
}

MediaPlayerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MediaPlayerMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav style="background-color: black" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
        
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">MediaPlayerMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    @if (TempData["storeUsername"] == null)
                            {
                               
                              
        
                            <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">

                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Display" asp-action="Index">Display</a>
                        </li>

                

                        <li class="nav-item glyphicon glyphicon-user">
                            <a class="nav-link text-light " asp-area="" asp-controller="Registration" asp-action="Index">Register</a>
                        </li>


                        <li class="nav-item glyphicon glyphicon-log-in">
                            <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                    </ul>
                    }

                    else
                    {
                        <ul class="nav navbar-nav ml-auto ">
                            <li class="nav-item text-light">


                                Welcome @TempData["name"]!<br />
                                @TempData["storeUsername"]
                               
                            </li>
                            &nbsp;&nbsp;
                            <li class="nav-item">
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Login")'" > Logout
                              </button>
                              
                            </li>
                        </ul>

                    }










                </div>
            </div>
            </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MediaPlayerMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>